linux-api-headers;linux-pam
glibc
gmp
mpfr
mpc
zlib
libstdcpp
gcc
m4;ncurses;attr;findutils;bzip2;gawk;diffutils;xz;make;tcl;expat;libffi;which
zstd;bison;readline;acl;libcap;patch;file;less;expect
bash;gettext;gdbm;gzip;tar;libelf;bc;dejagnu
perl;sed;binutils;libtool
openssl;autoconf;texinfo;groff
automake;grep;python3
coreutils
base